### ISSUE TITLE
Compile error - for loop declaration

### ISSUE THREAD

**Issue by maplebird** [shreepads/pdfcrack-mp#23]
Attempting to compile on RHEL 7.2 (Maipo) yields the following error:

`passwords.c:196:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (unsigned int i=0; i<patternLen; i++)`

Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by maplebird** [comment]
Just had the same error on Ubuntu 14.04.3 LTS (AWS version).

**Comment by shreepads** [comment]
Hey there. I think the GCC options can be changed to not treat warnings as
errors and that should solve this.

Tbh I have stopped working on this as I wasn't getting any feedback from
anyone actually using it.

**Comment by maplebird** [comment]
Sorry, I realized I was looking at a slightly wrong section.  I've edited the post above with the actual error, however this is resolved pretty easily by adding the -std=c99 flag in Makefile:

`CFLAGS += -Wall -Wextra -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -O3 -g -fopenmp -std=c99`

Sadly, getting a buffer overflow when trying to run make test, and trying to run brute force against an actual PDF file results in it only running on a single core no matter what command-line options I use.

I wish I knew any C to actually troubleshoot it.

PS: I didn't even know about this until an hour ago 😃

**Comment by shreepads** [comment]
Ok makes sense. Actually this is a problem on some distros not all. On some
GCC uses c99 by default. Can add this to issue #22.

If you can open a new one for the overflow error I can take a look on the
weekend.

Are you using one of the test PDFs? If not can you see if its not a new pdf
version causing the problem? See issue # 16 and 18 just in case.

**Comment by mtucker6784** [comment]
Cheers on the Makefile find, that worked well! (gcc 4.8.4 / Ubu 14)

**Comment by shreepads** [comment]
Finally got around to adding the std=c99 flag to CFLAGS :-)

Tested on AWS using the AMI: Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type - ami-b63769a1
Working fine

Tried to run the same on AWS using the AMI: Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-80861296
But this resulted in a buffer overflow error as reported by @maplebird 
This was fixed by correcting a bug in runCrackRev3_o in the pattern method section.
Tested and working correctly now.

Merged into baseopenmp, closing the defect. Also gets some way to solving issue #22
